


class Constants {

    companion object {
        const val BASE_URL = "http://103.99.202.37"

        const val WELCOME_URL="eduhub/api/welcone-screen-data"
        const val GET_STARTED_URL="eduhub/api/get-started-button-scree-data"
        const val REGISTER="eduhub/api/student-register"
        const val GRADES_URL="eduhub/api/get-grade-data"
        const val VERIFY_OTP="eduhub/api/verify-mobile-otp"
        const val LOGIN="eduhub/api/student-login"
        const val CHANGE_PASSWORD="eduhub/api/student-change-password"
        const val ABOUT="eduhub/api/get-aboutus-data"
        const val CONTACT_US="eduhub/api/contact-us"
        const val PRIVACY_POLICY="eduhub/api/get-pivacy-policy-data"
        const val SEND_OTP="eduhub/api/email/otp"
        const val TERMS_AND_CONDITIONS="eduhub/api/get-term-condition-data"
        const val HOME_BANNER="eduhub/api/home-page-banner"
        const val NOTIFICATION="eduhub/api/set-notification"
        const val GET_SUBJECT="eduhub/api/get-subject-by-grade"
        const val GET_TOP_PICK="eduhub/api/get-top-pick-chapter"
        const val GET_TOP_TEACHER="eduhub/api/get-top-teacher-home-screen"
        const val USER_DETAIL="eduhub/api/user-detail"
        const val FORGOT_PASSWORD="eduhub/api/forgot-password"
        const val RESET_FORGOT_PASSWORD="eduhub/api/update-new-password"
        const val GET_CHAPTERS="eduhub/api/get-chapter-list"
        const val SOCIAL_LOGIN="eduhub/api/social/login"
        const val CHAPTER_RELATED_VIDEO="eduhub/api/get-chapter-related-video"
        const val HOME_DATA_API="eduhub/api/home/data"
        const val UPDATE_PROFILE="eduhub/api/update/student/profile"
        const val FAV_UNFAV_TEACHER="eduhub/api/fav/unfav/teacher"
        const val FAV_TEACHER_LIST="eduhub/api/fav/teacher/list"
        const val TEACHER_PROFILE="eduhub/api/teacher/detail/profile"
        const val TOPIC_DETAILS="eduhub/api/topic/detail/pdf"
        const val SEARCH_API="eduhub/api/search"
        const val ADMIN_DETAILS="eduhub/api/contact/detail/admin"
        const val TOPIC_LIST="eduhub/api/get/subject/topic"
        const val TOPIC_DETAILS_LIST="eduhub/api/fetch/topicVideo/worksheet"
        const val SUBJECT_LIST="eduhub/api/subject/list"
        const val RATING="eduhub/api/add/rating"
        const val GET_SUBJECTS_BY_ID="eduhub/api/subject/list/teacher"
        const val TEST_LIST="eduhub/api/test/list"
        const val TEST_QUESTION_LIST="eduhub/api/question/list"
        const val SUBMIT_ANS="eduhub/api/question/submit"
        const val PAST_QUE_CATEGORY="eduhub/api/past/question/category/list"
        const val PAST_QUESTION_PPRS="eduhub/api/past/questions"
        const val GET_ALL_NOTIFICATIONS="eduhub/api/get/all/notifications"
        const val TEST_SCORE="eduhub/api/test/score"
         const val TYPE_USER="type_user"
        const val GET_ALL_CHAT_MESSAGES = "eduhub/api/get-all-chat"
        const val SEND_MESSAGE = "eduhub/api/send-message"
        const val RECEIVE_MESSAGE = "eduhub/api/recent-messages"
        const val GET_NOTI_COUNT = "eduhub/api/new/count/notification"
        const val FETCH_ALL_NOTIFICATIONS = "eduhub/api/get/all/notifications"
        const val RECENT_CONTINUE_TOPIC = "eduhub/api/recent/continue/topic"
        const val TEST_SUMMARY = "eduhub/api/test/summary"
        const val GET_CONVERSATION_ID = "eduhub/api/conversation"
        const val LOGINN="login"
    }
}
