


class Constants {
    companion object {
        const val BASE_URL = "https://eduhubteacher.com/"
        const val WELCOME_URL="api/welcone-screen-data"
        const val GET_STARTED_URL="api/get-started-button-scree-data"
        const val REGISTER="api/student-register"
        const val GRADES_URL="api/get-grade-data"
        const val VERIFY_OTP="api/verify-mobile-otp"
        const val LOGIN="api/student-login"
        const val CHANGE_PASSWORD="api/student-change-password"
        const val ABOUT="api/get-aboutus-data"
        const val CONTACT_US="api/contact-us"
        const val PRIVACY_POLICY="api/get-pivacy-policy-data"
        const val SEND_OTP="api/email/otp"
        const val TERMS_AND_CONDITIONS="api/get-term-condition-data"
        const val HOME_BANNER="api/home-page-banner"
        const val NOTIFICATION="api/set-notification"
        const val GET_SUBJECT="api/get-subject-by-grade"
        const val GET_TOP_PICK="api/get-top-pick-chapter"
        const val GET_TOP_TEACHER="api/get-top-teacher-home-screen"
        const val USER_DETAIL="api/user-detail"
        const val FORGOT_PASSWORD="api/forgot-password"
        const val RESET_FORGOT_PASSWORD="api/update-new-password"
        const val GET_CHAPTERS="api/get-chapter-list"
        const val SOCIAL_LOGIN="api/social/login"
        const val CHAPTER_RELATED_VIDEO="api/get-chapter-related-video"
        const val HOME_DATA_API="api/home/data"
        const val UPDATE_PROFILE="api/update/student/profile"
        const val FAV_UNFAV_TEACHER="api/fav/unfav/teacher"
        const val FAV_TEACHER_LIST="api/fav/teacher/list"
        const val TEACHER_PROFILE="api/teacher/detail/profile"
        const val TOPIC_DETAILS="api/topic/detail/pdf"
        const val SEARCH_API="api/search"
        const val ADMIN_DETAILS="api/contact/detail/admin"
        const val TOPIC_LIST="api/get/subject/topic"
        const val TOPIC_DETAILS_LIST="api/fetch/topicVideo/worksheet"
        const val SUBJECT_LIST="api/subject/list"
        const val RATING="api/add/rating"
        const val GET_SUBJECTS_BY_ID="api/subject/list/teacher"
        const val TEST_LIST="api/test/list"
        const val TEST_QUESTION_LIST="api/question/list"
        const val SUBMIT_ANS="api/question/submit"
        const val PAST_QUE_CATEGORY="api/past/question/category/list"
        const val PAST_QUESTION_PPRS="api/past/questions"
        const val GET_ALL_NOTIFICATIONS="api/get/all/notifications"
        const val TEST_SCORE="api/test/score"
         const val TYPE_USER="type_user"
        const val GET_ALL_CHAT_MESSAGES = "api/get-all-chat"
        const val SEND_MESSAGE = "api/send-message"
        const val RECEIVE_MESSAGE = "api/recent-messages"
        const val GET_NOTI_COUNT = "api/new/count/notification"
        const val FETCH_ALL_NOTIFICATIONS = "api/get/all/notifications"
        const val RECENT_CONTINUE_TOPIC = "api/recent/continue/topic"
        const val TEST_SUMMARY = "api/test/summary"
        const val GET_CONVERSATION_ID = "api/conversation"
        const val GET_UNIQUE_ID = "api/test/unique/id"
        const val LESSON_LIST = "api/lesson/list"
        const val WORKSHEET_LIST = "api/worksheet/list"
        const val LOGINN="login"
        const val GET_NOTIFICATION_STATUS="api/get/notification/status"
    }
}
